version: 0.0
os: linux
files:
  - source: /docker-compose.yml
    destination: /home/ec2-user/docker-compose.yml
  - source: /appspec.yml
    destination: /home/ec2-user/appspec.yml
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ec2-user
