version: 0.2

env:
  variables:
    AWS_REGION: "ap-south-1"
    ECR_REPOSITORY: "todo-app"
    IMAGE_TAG: "latest"
    ECR_URI: "491085408142.dkr.ecr.ap-south-1.amazonaws.com/todo-app"
    AWS_ACCOUNT_ID: "491085408142"

phases:
  install:
    runtime-versions:
      docker: 19
    commands:
      - echo "Installing AWS CLI and Docker"
      - apt-get update -y
      - apt-get install -y awscli
      - aws --version
      - echo "Logging in to Amazon ECR"
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_URI

  pre_build:
    commands:
      - echo "Building the Docker image"
      - docker build -t $ECR_REPOSITORY:$IMAGE_TAG .

  build:
    commands:
      - echo "Tagging Docker image"
      - docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_URI:$IMAGE_TAG
      - echo "Pushing Docker image to Amazon ECR"
      - docker push $ECR_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "Build and push completed successfully"

artifacts:
  files:
    - appspec.yml
    - taskdef.json  # Optional, for ECS
  discard-paths: yes
